import json
from decimal import Decimal
from random import seed


def test_big_dataset():
    """
    Example using big autogenerated dataset
    """
    from stvpoll.scottish_stv import ScottishSTV

    seed(42)
    with open("stvpoll_testing/70 in 35.json") as infile:
        vote_data = json.load(infile)
    poll = ScottishSTV(candidates=vote_data["candidates"][:70], seats=34)
    for b in vote_data["ballots"]:
        poll.add_ballot(b)

    result = poll.calculate()
    assert result.complete
    assert tuple(result.as_dict()["rounds"][-1]["vote_count"].values())[7] == 2.03862


def test_tiebreak_history():
    """Unreasonably high quota"""
    from stvpoll.scottish_stv import ScottishSTV

    example_candidates = ("Andrea", "Robin", "Gorm")
    example_ballots = (
        (("Andrea",), 3),
        (("Robin",), 2),
        (("Gorm", "Robin"), 1),
        ((), 3),
    )
    poll = ScottishSTV(seats=1, candidates=example_candidates, quota=lambda x, y: 100)
    for b in example_ballots:
        poll.add_ballot(*b)
    result = poll.calculate()
    assert not result.randomized
    assert result.complete
    assert result.empty_ballot_count == 3


def test_pedantic_order_no_random():
    from stvpoll.scottish_stv import ScottishSTV

    poll = ScottishSTV(
        seats=2, candidates=[1, 2, 3], random_in_tiebreaks=False, pedantic_order=True
    )
    poll.add_ballot([1, 2], 2)
    poll.add_ballot([2, 1], 2)
    poll.add_ballot([3])
    result = poll.calculate()
    assert not result.complete


def test_pedantic_order():
    from stvpoll.scottish_stv import ScottishSTV

    seed(1)
    poll = ScottishSTV(seats=2, candidates=[1, 2, 3, 4, 5], pedantic_order=True)
    poll.add_ballot([1, 2], 5)
    poll.add_ballot([2, 1], 4)
    poll.add_ballot([3], 4)
    poll.add_ballot([4, 2], 2)
    poll.add_ballot([4, 1])
    result = poll.calculate()
    assert result.complete
    assert result.as_dict()["quota"] == 6
    assert result.elected_as_tuple() == (1, 2)


def test_vote_transfers():
    from stvpoll.scottish_stv import ScottishSTV

    seed(42)
    candidates = (6041, 6042, 6044, 6038, 6034, 6043, 6040, 6039, 6035, 6036, 6037)
    ballots = [
        [6039, 6043, 6042, 6044, 6034],
        [6043, 6042, 6039, 6036, 6037, 6044, 6041, 6040, 6038, 6035, 6034],
        [6038, 6042, 6036, 6035, 6034, 6037, 6040, 6039, 6043, 6044, 6041],
        [6034, 6035, 6036, 6037, 6038],
        [6037, 6038, 6044],
        [6039, 6038, 6037, 6042, 6044],
        [6038, 6039, 6037, 6036, 6035, 6034, 6040, 6042],
        [6036, 6035, 6039, 6040, 6042, 6037, 6041, 6043, 6044],
        [6034, 6038, 6039, 6040, 6042],
        [6034, 6036, 6035, 6040, 6042, 6043, 6044, 6041, 6039, 6037, 6038],
        [6037, 6042, 6040, 6044, 6035],
        [6034, 6042, 6037, 6044, 6036, 6035, 6043, 6040, 6039, 6041, 6038],
        [6037, 6043, 6038, 6035, 6034, 6036, 6039, 6040, 6041, 6042, 6044],
        [6036, 6035, 6034, 6038, 6041, 6042, 6040],
        [6037, 6044, 6042, 6040, 6034, 6036, 6035, 6038, 6041],
    ]
    poll = ScottishSTV(
        seats=5,
        candidates=candidates,
        random_in_tiebreaks=True,
        pedantic_order=True,
    )
    for b in ballots:
        poll.add_ballot(b)
    result = poll.calculate()
    assert poll.quota == 3
    assert result.rounds[1].votes[6038] == Decimal(2.5)
